project:
  type: website
  output-dir: docs

website:
  title: "heejoon blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/heejoonkang
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



